Hotel_Booking_System/Models/Room_View.cs
using Hotel_Booking_System_DBContext.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hotel_Booking_System.Models
{
    public class Room_View
    {
        public int id { get; set; }

        public int Hotel_Category_id { get; set; }
        public IEnumerable<Hotel_Categories> categories { get; set; }

        public int floor_id { get; set; }
        public IEnumerable<Floor> floors { get; set; }


        public int room_type_id { get; set; }
        public IEnumerable<Room_Types> room_types { get; set; }

        public string room_no { get; set; }
        public decimal day_price { get; set; }
        public string description { get; set; }
        public int Success { get; set; }

        public IEnumerable<Room_List> rooms { get; set; }
    }
    public class Room_List
    {
        public string Hotel_category { get; set; }
        public string Room_No { get; set; }
        public string Floor { get; set; }
        public string Room_Type { get; set; }
        public string Discption { get; set; }
    }
}

Hotel_Booking_System/Controllers/RoomController.cs
using Hotel_Booking_System.Models;
using Hotel_Booking_System_DBContext.Models;
using Hotel_Booking_System_DBContext.Services;
using System.Linq;
using System.Web.Mvc;

namespace Hotel_Booking_System.Controllers
{
    public class RoomController : Controller
    {
        Hotel_System_DBContext db;
        Room_View Room;
        // GET: Room
        public ActionResult Rooms()
        {
            db = new Hotel_System_DBContext();
            Room = new Room_View()
            {
                categories = db.Hotel_Categories.ToList(),
                floors = db.Floors.ToList(),
                //room = new Hotel_Booking_System_DBContext.Models.Room(),
                room_types = db.Room_Types.ToList(),
                Success = 0,
                rooms = (from rm in db.Rooms.DefaultIfEmpty()
                        from fr in db.Floors.Where(x=> x.id == rm.floor_id).DefaultIfEmpty()
                        from hc in db.Hotel_Categories.Where(x => x.id == fr.hotel_category_id).DefaultIfEmpty()
                        from rt in db.Room_Types.Where(x=> x.id == rm.room_type_id).DefaultIfEmpty()
                        select new Room_List
                        {
                            Discption = rm.description,
                            Floor = fr.floor_no,
                            Hotel_category = hc.location,
                            Room_No = rm.room_no,
                            Room_Type= rt.name_type
                        }
                        ).ToList(),
            };



            return View(Room);
        }

        [HttpPost]
        public ActionResult Rooms(Room_View room)
        {
            db = new Hotel_System_DBContext();
            Room_services service = new Room_services(new Hotel_Booking_System_DBContext.Models.Room() 
            {
                day_price = room.day_price,
                description = room.description,
                floor_id = room.floor_id,
                id = room.id,
                is_avaliable = true,
                room_no = room.room_no,
                room_type_id = room.room_type_id,
                
            });
            service.InsertOrUpdate();
            room.Success = 1;
            room.categories = db.Hotel_Categories.ToList();
            room.floors = db.Floors.ToList();
            room.room_types = db.Room_Types.ToList();
            room.rooms = (from rm in db.Rooms.DefaultIfEmpty()
                              from fr in db.Floors.Where(x => x.id == rm.floor_id).DefaultIfEmpty()
                              from hc in db.Hotel_Categories.Where(x => x.id == fr.hotel_category_id).DefaultIfEmpty()
                              from rt in db.Room_Types.Where(x => x.id == rm.room_type_id).DefaultIfEmpty()
                              select new Room_List
                              {
                                  Discption = rm.description,
                                  Floor = fr.floor_no,
                                  Hotel_category = hc.location,
                                  Room_No = rm.room_no,
                                  Room_Type = rt.name_type
                              }
                      ).ToList();

            return View(room);
        }
    }
}

Hotel_Booking_System/Views/Room/Rooms.cshtml
@model Hotel_Booking_System.Models.Room_View
@{
    ViewBag.Title = "Rooms";
}

<style>
    .price::before {
        content: '€'
    }

    .price::after {
        content: '.00';
        font-size: 19px;
    }
</style>
<div class="row" id="searchpage" style="height:500px;">
    <div class="col-md-4">
        <h2 style="font-family:Arial;font-style:italic;color:white;background-color:lightseagreen;border-radius:20px; width:140px; padding:10px; text-align:center;">Rooms</h2>

        <div class="panel panel-default">
            <div class="panel-heading">Adding Rooms</div>
            <div class="panel-body">
                @using (Html.BeginForm("Rooms", "Room", FormMethod.Post))
                {
                    <div class="form-group">
                        <label for="room_no"> Room No </label>
                        @Html.EditorFor(model => model.room_no, new { htmlAttributes = new { @for = "room_no", @class = "form-control", @type = "text", @placeholder = "Enter Room No" } })


                        <label for="floor"> Floor </label>
                        @Html.DropDownListFor(model => model.floor_id, new SelectList(Model.floors, "id", "floor_no"), new { @for = "floor", @class = "form-control" })

                        <label for="room_type"> Room Type </label>
                        @Html.DropDownListFor(model => model.room_type_id, new SelectList(Model.room_types, "id", "name_type"), new { @for = "room_type", @class = "form-control" })

                        <label for="day_price">Day Price</label>
                        @Html.EditorFor(model => model.day_price, new { htmlAttributes = new { @for = "day_price", @class = "form-control", @type = "number", @placeholder = "Enter Day price" } })

                        <div class="panel-heading"> Hotel Description</div>
                        <div class="panel-body" style="position:relative;">
                            <label for="desc">Description</label>
                            @Html.TextAreaFor(model => model.description, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Day price", @for = "desc" } })

                        </div>
                        <button type="submit" value="submit" style="margin-top: 20px; background-color: lightseagreen; border-radius: 20px; width: 140px; padding: 10px;" class="btn btn-success pull-left align" data-bind="click: $root.reserve">
                            Add
                        </button>


                    </div>

                }
                @if (Model.Success == 1)
                {


                    <div class="alert alert-success" role="alert">
                        Save Is Success !
                    </div>
                }
            </div>

        </div>

    </div>

    <div class="col-md-8">

        <table class="table table-dark table-striped">
            <thead>
                <tr>
                    <th>Hotel Category</th>
                    <th>Room No</th>
                    <th>Floor</th>
                    <th>Room Type</th>
                    <th>Discription</th>

                </tr>
            </thead>
            <tbody>
                    @foreach (var item in Model.rooms)
                    {
                <tr>
                    <td>@item.Hotel_category</td>
                    <td>@item.Room_No</td>
                    <td>@item.Floor</td>
                    <td>@item.Room_Type</td>
                    <td>@item.Discption</td>

                </tr>
                    }

            </tbody>
        </table>



    </div>